### PR TITLE
Add support for Angular UI Router plugin

### PR DESCRIPTION
**Pull request by tusharr**

### CODE REVIEW

**Comment by tusharr** [comment]
There are more events that Angular UI Router supports for example $viewContentLoading, $viewContentLoaded, $stateNotFound, $stateChangeError that provide deeper insight into performance.

They are listed here:
https://github.com/angular-ui/ui-router/wiki

**Comment by nicjansma** [comment]
Hi Tushar!

This might be better suited just integrating the `$stateChangeStart` and `$stateChangeSuccess` events into the existing `plugins/angular.js` plugin.  What do you think?

**Comment by tusharr** [comment]
@nicjansma that is a good idea. Do you guys wanna make that change?

**Comment by nicjansma** [comment]
Available as part of https://github.com/SOASTA/boomerang/pull/98

**Pull request closed without merging**
