### PR TITLE
SOASTA 2018 Q1 Backport

### PR DESCRIPTION
**Pull request by nicjansma**
This is a backport of all of Akamai/SOASTA's contributions to boomerang from April 2017 (mPulse's version 1.452.0) through April 2018 (mPulse's version 1.568.0).

This backport also includes a [large update](226062fec27034da8ede3c2af96bbb981cf45bbb) to the JSDoc documentation of Boomerang.  We will be updating the [documentation site](https://soasta.github.io/boomerang/) after this has been merged.

# New Plugins
* Continuity plugin [Nic Jansma] 0f1ced9d5d4ebd1a8a5c813cdc2d03b696551ddb
* IFrameDelay plugin [Andreas Marschke] 3bfe3d7d5fea48fdef375195b5b493a5e74deebb
* PaintTiming plugin [Nic Jansma] 3418aea678822d66d4eda04a5de13de710b0209c

# New Features
* Boomerang: Documentation Updates [Nic Jansma] 226062fec27034da8ede3c2af96bbb981cf45bbb
* Boomerang: Add 'nocookie' flag if we couldn't set cookies [Nic Jansma] 94cfa617f6d767b7dc6938acceedb1231421e581
* Boomerang: Add BOOMR.utils.arrayFind function [Nigel Heron] 2a8b36dc7d826658207183cc6eeccd91f46021b0
* Boomerang: Capture BOOMR.page_ready() time after onload; [Nic Jansma] 9ef6d13469a39be5cef19e3fa1863c5f454c531b
* Boomerang: BOOMR.addVar() for single beacons [Nic Jansma] 9ef6d13469a39be5cef19e3fa1863c5f454c531b
* Boomerang: Configuration for locking beacon_url to specific patterns [Nic Jansma] e85fdf4c37ca41b6e859425a714f21cb723cb922
* Boomerang: LocalStorage support [Nigel Heron] 296e335c169ae36120b85cfd107cb3063e11256a
* History: Option to disable hard navigation in favor of BOOMR.page_ready() [Andreas Marschke] cd5ab8d101b3723d2278ec40698c005c2526c5ac
* NavigationTiming: Add a few NavigationTiming2 fields if available [Nic Jansma] b18ef55ddc71a8ad68224142e65e21e2afce3de3
* ResourceTiming: Add iframe and subdocument to initiatorType [jzyang] 94b92e505cb23c8179fe09b285cb22b5ea5c789e
* ResourceTiming: Add link.rel data to the ResourceTiming trie [Charles Vazac] a5f37895c0abb9c545164173358ad20ec0e27400
* SPA: Log aborted load beacons [Nigel Heron] 61732154e685c6ae5eb4c9371c77b7ca21285856
* SPA: markNavigationComplete() support [Nic Jansma] f253d1b5a5763bf9c0bc056de7df9ac7902c0365

# Bug Fixes
* Boomerang: Work around minification that breaks in IE8 and quirks mode [Nigel Heron] 603d5da85520d64ed76e54de2d43ec59774ef85f
* Boomerang: BOOMR.sendBeaconData refactor [Nic Jansma] 8b0ef735b50d5ba9cc710986507bb32182d7adde
* Boomerang: Override the load end-time with BOOMR_page_ready or param to page_ready() [Nigel Heron] 2ff1e2ad0a81602bfbd60fb9f1554df4ea845fd9
* Boomerang: sendBeacon: x-www-form-urlencoded [Nic Jansma] b5d99672f084f3e8c1ef72cdb38eb50679494ff5
* Boomerang: Workaround for document.write changing readyState after onload [Nigel Heron] 2822a79e0424cb4fdd4cab004c928388888f7aa1
* Angular: Don't trigger Route Change on $locationChangeStart if other events fire [Nic Jansma] 1cce81c00b83c6e849759079c4d0cbd325ae7d17
* Angular: Track navigations when only a $locationChangeStart fires [Nic Jansma] 031c1fbf33eb616e539b876d23bd785fac9fb7e4
* AutoXHR: Disable MutationObserver in IE 11 due to browser bugs [Nigel Heron] a99f09d06b5043a5a73a279c33c03f29d8f1ad1e
* AutoXHR: Do not extend the event timeout with each uninteresting mutation [Nigel Heron] 1fdfcdab4b96454327f7c316ef196443c7da620e
* AutoXHR: Don't wait for XHRs that .open() but don't .send() [Nigel Heron] 583536bb6566337e3396502ae9a8f54779d7b199
* AutoXHR: Fixes XHR after click missing beacon [Nic Jansma] 970ad46f829ccf5dce5372d9db3b9383d6f5d15a
* AutoXHR: If we don't instrument XHR open then don't instrument send either [Nigel Heron] 58b0879a55139a2233c8fae679afa76be284b983
* AutoXHR: Wait once up to 1,000ms after an uninteresting mutation [Nic Jansma] 69840cdfb31e710501ea4e0c55b2defc1cfb67a0
* Documentation: Misc JSDoc fixes [Nic Jansma] 9c3e86397e02fa8548fc82c28cf77c6ec81d0848
* Errors: Call removeEventListener before addEventListener [Charles Vazac] 2d2cfd0ba137180fab88bc9f8ded80747c314c98
* Errors: Check context in wrapFn [Charles Vazac] 1e79cd43a9b45bbdcad715dc245a2c4d0cde19a2
* Errors: Deduplicate calls to AddEventListener with the same arguments [Nigel Heron] 5f2a31a2c7dcee4178770052e9325838b45a12a5
* Errors: Don’t report IE error for freed script in event and timeout handlers [Nigel Heron] cd898d2e77f1eac32e4b083293c933cc170e3c31
* Errors: Loader Snippet to capture errors before Boomerang arrives [Nic Jansma] becae71e6733510239e16165636a3701b2a7d4dd
* Errors: Re-throw caught exceptions [Nic Jansma] c5fbfc50370a6d92b89c04f05b6e6302fa129669
* Errors: Remove certain file names from stacks [Nic Jansma] f66eb82d830f037ef0a804caea7b89d5185f221f
* Errors: Send during onload if autorun=false [Nic Jansma] 46c6f62102919a4f6245f18e4c421404851c97f9
* Errors: Wrap addEventListener at the end of the protocol chain [Nigel Heron] c443040ac39690811d41718816f422a1906e53b6
* NavigationTiming: Deprecate chrome.loadTimes [Nic Jansma] 3418aea678822d66d4eda04a5de13de710b0209c
* NavigationTiming: Don't include timestamps for events that haven't happened [Nic Jansma] 721ceb35fdec52177a3dadc3e373141b26bf826f
* NavigationTiming: Fix nt_nav_st [Nigel Heron] 8db295125802ad062415a74402dc759710c9e23e
* ResourceTiming: Additional checks and fixes for non-supported browsers [Nic Jansma] 4fe7ec0ea4f4607efe72c95136f74e9521b838ba
* RT: Always use loadEventEnd as the end load time [Nic Jansma] e70b3f1211a9f056407e190cdfdf73d19f913cae
* RT: Fix t_page and t_resp missing from the beacon [Nic Jansma] 6f1acad15284e700f244f446eede5105c427142b
* SPA: Calculate Front-End / Back-End even if ResTiming isn't enabled but the plugin is available [Nic Jansma] 45dacc62b530cd2e3cba6dfcf062f9f08cbb4a26
* SPA: Don't send beacons for SPA soft navs that don't change the URL and no resources are triggered [Nigel Heron] 0736a0d998ce0a1582499982be66950980885bf4
* SPA: Fix custom timers for SPA navigations [Nigel Heron] f35f912a2761cf5614c216f7861f7ea03cf0df50
* TPAnalytics: Don’t send boomerang error on TPAnalytics third party errors [Nigel Heron] 921538f74eaadcaa878e8bbc6e4722ec9637cc09

# Loader Snippet Update
* Boomerang Loader Snippet v10 [Nic Jansma] 0264088616104f9adb9cba8a6afdef4b472a43c4
* Documentation: Non-Blocking Loader Snippet and delayed snippet [Nic Jansma] 61290edbebf6681a10525d49eff3abefbe5ecfce
* Correctly detect our url on IE using non-standard loader [Philip Tellis] bda14f593c3b0b07e79aa98a5a71801bcb232778
* BOOMR.getMyURL() fix for PhantomJS 1 [Nigel Heron] a1ca8755108f76d051d8a0e520ff9369d7df545a
* Make self url detection work when loaded in primary window as well [Philip Tellis] fc4474680c27c251f9593a4d98fee326e6152dad

# Test Fixes
* Tests: Headless modern browser support (Chrome + Firefox) [Nic Jansma] 745792b27778d4da8a72e179ecc34d9ab43164cd
* Tests: Edge, IE and Safari e2e support [Nigel Heron] b1dd31bffd50c7c826c1fea869aa6782ab333ffa
* Test Framework: isJSONSupported() added [Nigel Heron] f9fe6476094a8f6c3e68bc26ece8f37b895f6625
* Prevent unload confirmation popup in tests [Nigel Heron] 791c58857a39dc74279f5f5cd5ea9c14423e9ca8
* Revive the SauceLabs code [Charles Vazac] b813ebf5862129da5122f39ed128043156406e30
* Update to new server timing header syntax [Charles Vazac] 2c375ec190c7f54ca769dade647d79d44b0d6813
* Upgrade "express-middleware-server-timing" [Charles Vazac] 8a4cb8da62d0ba72b55aef6c43995cba42319d74
* Test fixes [Nigel Heron] e4dc03e8da679bfb583f477ede4ea3eb390e09d7
* Modernize expressjs usage, which fixes express-middleware-server-timing [Charles Vazac] 69ae88299809eba7735fa5133a5153bbaa09348c
* Test fixes for modern browsers [Nic Jansma] 6fd3713a8dc7207bbd3515a399886f338260f424
* 14-errors/23-duplicate-event-listener: Fixes inconsistent failure and older browsers [Nic Jansma] d0b5c10a562ef82f5c05c06e34042ccc419a0a37
* Test framework helper function for IE [Nic Jansma] d734bcb63ffa6b724daa8fd764c55e8c931f9cc0
* 03-load-order/02-after-page-load-tag-manager.html: Reduce code duplication [Nic Jansma] 4cd19e2de5e231fce1926b90c0241ac9ec0f0680
* Fixes e2e-debug.js [Nic Jansma] 9f1f513ddc558a2f10af7a8347a82cbccafd8cfd
* 01-beacon-type/04-send-beacon: Change how sendBeacon is detected [Nic Jansma] bc893475850010442f1ee317b6eb9afe2174ba4b
* 01-beacon-type/0123: Disable sendBeacon so we can inspect ResourceTiming for the correct type [Nic Jansma] f67eac238123e6db8493cafa21d564b57e91a940
* Fixes 00-basic/09-overrides [Nic Jansma] 3201f028e60618d59101d3830c49f386ded66090
* Check that all beacons pass basic validation [Nigel Heron] eacde8c3b2e5fe6de7d9ed86fa5c44d5bff4c05a
* Misc changes for Boomerang [Andreas Marschke] a2acc34bf0540d98405f98ca90b0d48a278e11b7
* Instrument Express requests with express-middleware-server-timing [Charles Vazac] 42d678208d9f6d25d851c406939e00b0a7e39425
* Misc test fixes [Andreas Marschke] 6e36d1706081fd88171001a371eb2d6f0b8e1f24
* Misc test framework fixes [Nigel Heron] d0b738219e9e090e29ea1447944087e8e8fd6a50
* Test fixes [Nigel Heron] 9f097eeb010b5eddd269d0107687bdd566554e03
* Use floor instead of round to match navtiming plugin [Nigel Heron] a45b2c2ab29ca84152ee56ac7afa013b3cd2b3ce

# Misc
* Updated package-lock.json [Nic Jansma] d536df4c7e0310b38cffa26fc40f5d37388a74fe
* Gruntfile: Allow passing in commit via commandline [Nic Jansma] 5b371dfd11dc597c680d2315bcae898ef7e79e84
* Package.json: Add blueimp-md5, error-stack-parser and jsurl at versions we've embedded them in for Snyk [Nic Jansma] c91c7117402fd3dab1634d95f0c80c8a46f03564
* Plugin init cleanup [Nic Jansma] 73c2513401b67d3e0bebd003bb2e143ed4838264
* BOOMR.log: Add timestamp [Nic Jansma] dda7f2b18e5d8a3a6f2605bf9778bb317907943b
* Miscellaneous cleanup [Nigel Heron] e815d9c5e37d97ab2a436b40e329aa824860a911
* Warn on window and document overrides (debug builds only) [Charles Vazac] f01f3969cd3b7f91b4af710f635d638d56a8c543
* PCI compliance fixes [Nic Jansma] a98dfd337df1ddfbb5918598faa228f4d3777a8d
* Update copyrights [Nigel Heron] cc058d73d21d42a1b627813558d9296851d019bd

### CODE REVIEW

**Comment by Krinkle** [comment]
> PaintTiming plugin [Nic Jansma] 3418aea
> [..]
> NavigationTiming: Add a few NavigationTiming2 fields if available [Nic Jansma] b18ef55

@nicjansma This commit ads new use of `chrome.loadTimes()`, but this is problematic for two reasons:

1. It is not considered a [Navigation Timing 2 field](https://www.w3.org/TR/navigation-timing-2/). The proprietary `firstPaint` field provided via `chrome.loadTimes()`, or (like Firefox/IE) was a non-standard extension to the NavigationTiming1 spec (performance.timing). It was standardised as part of the Paint Timing spec, not the Navigation Timing 2 spec. Where Navigation Timing 2 specifies access via `performance.getEntriesByType("navigation")`, Paint Timing specifies access via `performance.getEntriesByType("paint")`. See also <https://www.w3.org/TR/paint-timing/>. This interface is already available in Chrome and should be used instead.

2. The `chrome.loadTimes()` API was deprecated last year in Chrome 64 (December 2017) with console warnings, and is to be removed sometime later this year. See also <https://bugs.chromium.org/p/chromium/issues/detail?id=621512> and <https://developers.google.com/web/updates/2017/12/chrome-loadtimes-deprecated>

Perhaps it makes sense to move this to the paint-timing plugin and trigger only if the Paint Timing data was unavailable, or even just removed in general? That would avoid introducing significant use of the deprecated `chrome.loadTimes()` interface for the common case.

**Comment by Krinkle** [comment]
> Boomerang: Work around minification that breaks in IE8 and quirks mode [Nigel Heron] 603d5da

@querymetrics I couldn't find which version of UglifyJS of which configuration is used but note that jQuery ran into similar issues, and there, and they found a way through simple configuration. This may be preferred as it results in a smaller bundle size, and also has the benefit of not requiring manual code changes that are hard to maintain.

Specifically:

* The `output.ie8: true` option, ensures both the mangle and compress phases maintain compatibility with IE8 and Android 4.0. Such as for `obj['true']` vs `obj.true`. – https://github.com/jquery/jquery/commit/c9efd11f47c68f0537c8ea535b8d6a9c6d667175

**Comment by bluesmoon** [comment]
@Krinkle, we've used `chrome.loadTimes` since 2010, so this isn't new usage.  You'll also notice in the latest version of the file, this is only limited to Chrome versions that do not support NT2.

**Comment by Krinkle** [comment]
@bluesmoon Aha, I see now that after adding the new caller with b18ef55, another commit 3418aea678822d changed it to be conditional as you describe. However, there was still a duplicate version of that code bock left unconditional, but I see that's been fixed up since with 85aaefd75. I guess this was due to a merge conflict or something?

Anyhow, Thanks!

**Pull request merged**
